spring:
  application:
    name: servico-de-gateway
  cloud:
    gateway:
      routes:
        - id: servico-de-usuario
          uri: lb://servico-de-usuario
          predicates:
            - Path=/usuario/**

        - id: servico-de-cartao
          uri: lb://servico-de-usuario
          predicates:
            - Path=/cartao/**

        - id: servico-de-log
          uri: lb://servico-de-usuario
          predicates:
            - Path=/log/**

        - id: servico-de-autenticacao
          uri: lb://servico-de-autenticacao
          predicates:
            - Path=/usuario-autenticado/**


eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

server:
  port: 8765
